name: Format check

on:
  pull_request:
  push:
    branches:
      - main
      - staging
      - trying

jobs:
  check:
    name: Format check
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Formatting
        run: cargo fmt -- --check
