name: Publish Hermit environment

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish_image:
    name: Publish container image
    runs-on: ubuntu-latest

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: hermit-os
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create dockerfile for Ubuntu
      run: |
        cat << END > Dockerfile
        FROM ubuntu:latest
        RUN apt update
        RUN apt install -y --no-install-recommends libcap-ng0 libseccomp2 qemu-system-x86 net-tools virtiofsd
        END
    - name: Build and push container
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/hermit-os/hermit_env:latest
    - name: Create dockerfile for Alpine
      run: |
        cat << END > Dockerfile
        FROM alpine:latest
        RUN apk add --no-cache qemu qemu-system-x86_64 libseccomp libcap-ng virtiofsd
        END
    - name: Build and push container
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/hermit-os/hermit_env_alpine:latest
    
