name: Publish Hermit environment

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish_image:
    name: Publish container image
    runs-on: ubuntu-latest

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: hermitcore
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create dockerfile for Ubuntu
      run: |
        cat << END > Dockerfile
        FROM rust:bookworm as builder
        RUN apt update
        RUN apt install -y --no-install-recommends libcap-ng-dev libseccomp-dev
        RUN cargo install --git https://gitlab.com/virtio-fs/virtiofsd.git
        FROM bookworm:latest
        RUN apt update
        RUN apt install -y --no-install-recommends libcap-ng libseccomp qemu-system-x86 qemu-system-x86-microvm net-tools
        COPY --from=builder /root/.cargo/bin/virtiofsd /usr/bin/virtiofsd
        RUN chmod 0755 /usr/bin/virtiofsd
        END
    - name: Build and push container
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/hermitcore/hermit_env:latest
    - name: Create dockerfile for Alpine
      run: |
        cat << END > Dockerfile
        FROM alpine:latest
        RUN apk add --no-cache qemu qemu-system-x86_64
        END
    - name: Build and push container
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/hermitcore/hermit_env_alpine:latest
    
