name: Publish Hermit environment

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 6'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish_image:
    name: Publish container image
    runs-on: ubuntu-latest

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: hermitcore
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create dockerfile
      run: |
        cat << END > Dockerfile
        FROM alpine:3.15
        RUN apk add --no-cache qemu-system-x86_64 qemu-modules
        END
    - name: Build and push container
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/hermitcore/hermit_env:latest
